### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by miyamo386** [miyamo386/furima-39791#21]
# 自身のフリマアプリのURL
https://furima-39791.onrender.com

# Basic認証のIDとパスワード
ID                 admin
パスワード  2222

# 出品者用のメールアドレスとパスワード
メールアドレス  test@tarou.co.jp
パスワード　　 11111test

# 購入者用のメールアドレスとパスワード
メールアドレス hanako@test.co.jp
パスワード　　 22222test

**Comment by snkw-works** [comment]
@miyamo386 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
#### 商品出品機能
- [x] **入力された販売価格によって、販売手数料や販売利益が変わるよう修正しましょう(JavaScriptを使用して実装すること)**
出品機能・編集機能において、エラーハンドリングによって出品ページに戻ったあと、価格を再入力しても販売手数料や利益が変わらなくなります。どの状態でも変わるように修正をお願いします。

https://github.com/miyamo386/furima-39791/assets/54050089/088de151-be20-46f3-b544-7d5abf7b25e1

#### 商品詳細機能
- [x] **商品出品時に登録した情報（商品名・商品画像・販売価格・配送料負担・商品説明・出品者名・カテゴリー・商品の状態・発送元の地域・発送日の目安・○○をもっと見る）が、見本アプリと同様の形で出力されるよう修正しましょう**
「出品者名」が正しく表示されていない状態です。
<img width="541" alt="スクリーンショット 2024-02-01 10 04 06" src="https://github.com/miyamo386/furima-39791/assets/54050089/5dc18984-bab1-4d58-8d8f-c43e6768f638">

#### 商品編集機能
- [x] **ログアウト状態の場合は、商品情報編集ページへ遷移しようとすると、商品の販売状況に関わらずログインページに遷移すること**
ログインページではなく、エラーページに遷移してしまいます。
<img width="833" alt="スクリーンショット 2024-02-01 10 11 26" src="https://github.com/miyamo386/furima-39791/assets/54050089/3e6607c2-fadd-4000-b700-18f6fc98ceb8">


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by miyamo386** [comment]
挙動確認ありがとうございます。

修正しました。
再度フォーム提出をしますので、ご確認お願い致します。

**Comment by snkw-works** [comment]
@miyamo386 さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！ **LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by miyamo386** [comment]
最終課題LGTM、ありがとうございました！

これまでの学習を糧に、転職活動とエンジニアとして励んで参ります。

プログラミングとても楽しかったです！！
